### Importing the library

In [54]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 


In [55]:
dataset =pd.read_csv('customer_data.csv')
dataset.head()

,rowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,63197226,Jones,747,Spain,Male,50,3,144015.61,1,1,0,83512.69,0
1,2,98496222,Moore,772,Germany,Female,47,2,26035.99,2,0,0,23215.95,1
2,3,83252408,Davis,394,Spain,Male,27,7,103986.79,1,1,0,75593.36,1
3,4,83104818,Johnson,650,Italy,Female,20,4,68759.16,3,1,1,43626.64,1
4,5,31092624,Martin,701,France,Female,28,5,235868.08,4,1,0,65916.50,0


In [56]:
x =dataset.iloc[:,3:13].values 
y =dataset.iloc[:,13].values 


In [57]:
x,y

(array([[747, 'Spain', 'Male', ..., 1, 0, 83512.69],
        [772, 'Germany', 'Female', ..., 0, 0, 23215.95],
        [394, 'Spain', 'Male', ..., 1, 0, 75593.36],
        ...,
        [362, 'Germany', 'Male', ..., 0, 1, 26411.89],
        [724, 'Italy', 'Female', ..., 1, 0, 65108.48],
        [530, 'Germany', 'Female', ..., 1, 1, 149724.84]],
       shape=(20000, 10), dtype=object),
 array([0, 1, 1, ..., 0, 0, 0], shape=(20000,)))

In [58]:
#Encoding categorical data 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
labelencoder_x_1 =LabelEncoder() 
x[:,1] =labelencoder_x_1.fit_transform(x[:,1]) 
labelencoder_x_2 =LabelEncoder() 
x[:,2] =labelencoder_x_2.fit_transform(x[:,2]) 
x

array([[747, 4, 1, ..., 1, 0, 83512.69],
       [772, 1, 0, ..., 0, 0, 23215.95],
       [394, 4, 1, ..., 1, 0, 75593.36],
       ...,
       [362, 1, 1, ..., 0, 1, 26411.89],
       [724, 2, 0, ..., 1, 0, 65108.48],
       [530, 1, 0, ..., 1, 1, 149724.84]], shape=(20000, 10), dtype=object)

In [59]:
# Split the dataset into the train and test data set 

from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=0) 


In [60]:
len(dataset)

20000

In [61]:
len(x_train)

16000

## Feature Scaling 

In [62]:
## Standrization and Normalization 
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
x_train_sc =sc.fit_transform(x_train) 
x_test_sc =sc.transform(x_test) 

In [63]:
# Classical ML 
from sklearn.tree import DecisionTreeClassifier 
model_dt =DecisionTreeClassifier() 
model_dt.fit(x_train_sc,y_train) 
pred =model_dt.predict(x_test_sc) 

In [64]:
#making the confusion metrix 
from sklearn.metrics import confusion_matrix 
cm =confusion_matrix(y_test,pred)  
print(cm)

[[2202  856]
 [ 667  275]]


In [65]:
from sklearn.metrics import accuracy_score 

print(round(accuracy_score(y_test,pred),2)*100)

62.0


In [66]:
# Classical ML 
from sklearn.ensemble import RandomForestClassifier 
model_rf =RandomForestClassifier() 
model_rf.fit(x_train_sc,y_train) 
pred2 =model_rf.predict(x_test_sc) 

In [67]:
cm =confusion_matrix(y_test,pred2)   
print(cm)


[[3050    8]
 [ 940    2]]


In [68]:
print(round(accuracy_score(y_test,pred2),2)*100)

76.0


## DEEP LEARNING 

In [71]:
#Import the library
import keras 
from keras.models import Sequential 
from keras.layers import Dense ,Input
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

import tensorflow as tf


In [72]:
# initilissing the ANN 
classifier =Sequential() 

# Add the inpput layer and first hidden layer  
classifier.add(Input(shape=(10,)))
classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform'))

# Second hidden layer
classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform'))

# Output layer 
classifier.add(Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))

In [75]:
# compling the ANN 
classifier.compile(optimizer= 'adam' ,loss = 'binary_crossentropy', metrics=['accuracy']) 
y_train[0] 

# Fiting the ANN to training set 
classifier.fit(x_train_sc,y_train,batch_size=10,epochs=200)

Epoch 1/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7461 - loss: 0.6065
Epoch 2/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7464 - loss: 0.5675
Epoch 3/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7464 - loss: 0.5664
Epoch 4/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.7464 - loss: 0.5664
Epoch 5/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.7464 - loss: 0.5663
Epoch 6/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7464 - loss: 0.5663
Epoch 7/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7464 - loss: 0.5664
Epoch 8/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7464 - loss: 0.5663
Epoch 9/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7464 - loss: 0.5663
Epoch 10/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7464 - loss: 0.5663
Epoch 11/200
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7464 - loss: 0.5663
Epoch 12/200
1600/1

In [76]:
y_pred_ann =classifier.predict(x_test_sc) 
y_pred_ann =(y_pred_ann>0.5) 

cm3 =confusion_matrix(y_test,y_pred_ann) 
print(cm3)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[3058    0]
 [ 942    0]]


In [77]:
from sklearn.metrics import accuracy_score

print(round(accuracy_score(y_test,y_pred_ann),2)*100)

76.0


In [80]:
# importing the few library's for the k-folds 
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense, Input

