### Importing the library

In [2]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 


In [3]:
dataset =pd.read_csv('customer_data.csv')
dataset.head()

,rowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,63197226,Jones,747,Spain,Male,50,3,144015.61,1,1,0,83512.69,0
1,2,98496222,Moore,772,Germany,Female,47,2,26035.99,2,0,0,23215.95,1
2,3,83252408,Davis,394,Spain,Male,27,7,103986.79,1,1,0,75593.36,1
3,4,83104818,Johnson,650,Italy,Female,20,4,68759.16,3,1,1,43626.64,1
4,5,31092624,Martin,701,France,Female,28,5,235868.08,4,1,0,65916.50,0


In [4]:
x =dataset.iloc[:,3:13].values 
y =dataset.iloc[:,13].values 


In [5]:
x,y

(array([[747, 'Spain', 'Male', ..., 1, 0, 83512.69],
        [772, 'Germany', 'Female', ..., 0, 0, 23215.95],
        [394, 'Spain', 'Male', ..., 1, 0, 75593.36],
        ...,
        [362, 'Germany', 'Male', ..., 0, 1, 26411.89],
        [724, 'Italy', 'Female', ..., 1, 0, 65108.48],
        [530, 'Germany', 'Female', ..., 1, 1, 149724.84]],
       shape=(20000, 10), dtype=object),
 array([0, 1, 1, ..., 0, 0, 0], shape=(20000,)))

In [6]:
#Encoding categorical data 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
labelencoder_x_1 =LabelEncoder() 
x[:,1] =labelencoder_x_1.fit_transform(x[:,1]) 
labelencoder_x_2 =LabelEncoder() 
x[:,2] =labelencoder_x_2.fit_transform(x[:,2]) 
x

array([[747, 4, 1, ..., 1, 0, 83512.69],
       [772, 1, 0, ..., 0, 0, 23215.95],
       [394, 4, 1, ..., 1, 0, 75593.36],
       ...,
       [362, 1, 1, ..., 0, 1, 26411.89],
       [724, 2, 0, ..., 1, 0, 65108.48],
       [530, 1, 0, ..., 1, 1, 149724.84]], shape=(20000, 10), dtype=object)

In [9]:
# Split the dataset into the train and test data set 

from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=0) 


In [10]:
len(dataset)

20000

In [11]:
len(x_train)

16000

## Feature Scaling 